---
language: node_js
node_js:
  - 4
  - 5

sudo: false

before_install:
  - "npm config set spin false"

env:
  global:
  - SAUCE_USERNAME=ember-cli-sauce-ci
  - SAUCE_ACCESS_KEY=be8498f4-3dc5-4256-94c6-40dd9247f2e6

install:
  - npm install

script:
  - npm test
